### ISSUE TITLE
Leave URL open for modification by the users of the package.

### ISSUE THREAD

**Issue by tsommie** [faso-dev/orange-money-burkina-sdk#18]
```php
    return static::isProduction()
            ? 'https://apiom.orange.bf:9007/payment'
            : 'https://testom.orange.bf:9008/payment';
```

I don't think the URL should be hardcoded into the project. This should be moved into the `.env` file. If Orange should update its API URL, everyone using this package will have to wait for the maintainers to update the code. I suggest leaving it open for modification by the users of the package.

I can make a PR.

**Comment by faso-dev** [comment]
> ```
>     return static::isProduction()
>             ? 'https://apiom.orange.bf:9007/payment'
>             : 'https://testom.orange.bf:9008/payment';
> ```
> 
> I don't think the URL should be hardcoded into the project. This should be moved into the `.env` file. If Orange should update its API URL, everyone using this package will have to wait for the maintainers to update the code. I suggest leaving it open for modification by the users of the package.
> 
> I can make a PR.

Yes i agree.

**Comment by tsommie** [comment]
So I will close the #17 PR and make another with the changes discussed on the review.

**Comment by faso-dev** [comment]
> So I will close the #17 PR and make another with the changes discussed on the review.

it's okey for me

**Comment by faso-dev** [comment]
@tsommie you can close this issue now ?
