### ISSUE TITLE
Using a strict float type-hint for amount.

### ISSUE THREAD

**Issue by tsommie** [faso-dev/orange-money-burkina-sdk#21]
```php
    /**
     * Transaction amount
     * @var float
     */
    private $amount;

    /**
     * @param float $amount
     * @return OrangeMoneyAPI
     */
    public function setAmount(float $amount): self
    {
        $this->amount = $amount;
        return $this;
    }
```

Using a `float` type-hint for this is a bit strict, it is possible that the value may come as an integer or string, I suggest using  `mixed` or `int|string`, what do you think?

**Comment by faso-dev** [comment]
The price being defined as a float, an integer will pass without worry.  On the other hand, a character string is not supported by the API of Orange Money.  So wouldn't it be a source of error?  a user who tries setAmount ("foo") will surely result in strange behavior.

**Comment by tsommie** [comment]
If that is done by the user, it is up to Orange to validate the input, the important thing is for our package to not fail to make the request at all.

There is a possibility that our users would be using this package with a PHP Framework Like Laravel and Symfony, or use this plugin alongside popular money handling packages like [Money PHP](https://moneyphp.org/en/stable/), like I do, if this is the case, Money PHP will always return its values as a string and if we are requiring a float value, our code will fail even before the request is made. 

Needless to say that this package is incompatible with Money PHP and probably Laravel.

**Comment by tsommie** [comment]
Orange money should receive the request and then reject it if the data supplied is invalid, I don't think it's our job to validate the data supplied by a user. So if a user supplies `foo` as amount, orange money should evaluate the input just like they would if an invalid client ID is supplied.

**Comment by faso-dev** [comment]
> Orange money should receive the request and then reject it if the data supplied is invalid, I don't think it's our job to validate the data supplied by a user. So if a user supplies `foo` as amount, orange money should evaluate the input just like they would if an invalid client ID is supplied.

Indeed, that's fine with me. We change the type-hint to mixed.
