### ISSUE TITLE
Property visibility scope.

### ISSUE THREAD

**Issue by tsommie** [faso-dev/orange-money-burkina-sdk#22]
```php
    /**
     * Transaction amount
     * @var float
     */
    private $amount;

    /**
     * @var string
     */
    private $otp;

    /**
     * @var string
     */
    private $username;

    /**
     * @var string
     */
    private $password;

    /**
     * @var
     */
    private $merchantNumber;

    /**
     * @var
     */
    private $clientNumber;

    /**
     * @var
     */
    private $referenceNumber = "";

    /**
     * @var string
     */
    private $url;
```

Using `private` on the properties makes it impossible to extend this class, I suggest using `protected`.

**Comment by faso-dev** [comment]
Here it is a class of end use and dedicated to a specific Orange Operator.  So I don't think another class inherits from this one.  However, we can think of a class of the type AbstractMobileMoney which it can have protected properties as well as protected methods which can also be abstract if we do not know in advance how to implement them.

**Comment by tsommie** [comment]
> Here it is a class of end use and dedicated to a specific Orange Operator. So I don't think another class inherits from this one. However, we can think of a class of the type AbstractMobileMoney which it can have protected properties as well as protected methods which can also be abstract if we do not know in advance how to implement them.

What if as a developer I would like to extend the class and not use it directly, Maybe I want to change how the XML template is constructed in `private function requestApi()` you've made this impossible just by using `private`, so my only option would be to develop a new package, what if I want to create another package that takes care of Orange Money, Coris Money and others, but because am a contributor here I choose to depend on this package to avoid writing a new Orange Money API code, this would be impossible with the current setup because I can not extend the classes.

The `O` in `SOLID` principle stands for `open–closed principle` and it states that `"A class should be open for extension, but closed for modification"`.

`private` is not a very popular thing to use unless you have a good reason for it, I can only spot it in a few places in the whole of Laravel 8 and Symfony 5 Frameworks, I don't see the need or good reason for it in this package.

**Comment by faso-dev** [comment]
> > Here it is a class of end use and dedicated to a specific Orange Operator. So I don't think another class inherits from this one. However, we can think of a class of the type AbstractMobileMoney which it can have protected properties as well as protected methods which can also be abstract if we do not know in advance how to implement them.
> 
> What if as a developer I would like to extend the class and not use it directly, Maybe I want to change how the XML template is constructed in `private function requestApi()` you've made this impossible just by using `private`, so my only option would be to develop a new package, what if I want to create another package that takes care of Orange Money, Coris Money and others, but because am a contributor here I choose to depend on this package to avoid writing a new Orange Money API code, this would be impossible with the current setup because I can not extend the classes.
> 
> The `O` in `SOLID` principle stands for `open–closed principle` and it states that `"A class should be open for extension, but closed for modification"`.
> 
> `private` is not a very popular thing to use unless you have a good reason for it, I can only spot it in a few places in the whole of Laravel 8 and Symfony 5 Frameworks, I don't see the need or good reason for it in this package.

`requestApi` is private simply because it is for internal use. The code found in this method can perfectly be moved into `processPayment`. This is a method that is not meant to be used outdoors.

However, as you pointed out, we are going to change the visibility of properties and methods for the extension.

The `requestApi` method always remains `private` and `processPayment` becomes `protected` thus giving the user the possibility to implement his own logic.

**Comment by tsommie** [comment]
Ok
