### ISSUE TITLE
cURL error code 28

### ISSUE THREAD

**Issue by saifonglee** [faso-dev/orange-money-burkina-sdk#30]
Salut, 
deja merci pour ce travail abattu. cela facilite un temps soit peu ce processus d'integration de l'API Orange Money dans nos differents projet web.
J'ai une preoccupation: j'obtiens cette erreur lorsque j'essai de faire un paiement.
`Failed to connect to testom.orange.bf port 9008 after 130629 ms: Connection timed out`
J'ai modifier le `connect_timeout`, `read_timeout` et le `timeout` mais c'est toujours pareille.

savez-vous pourquoi cette erreur persite? 
pouvez-vous m'apporter votre assistance? 
Merci d'avance.

**Comment by faso-dev** [comment]
Le temps de réponse dépends fortement du serveur de Orange Burkina.

Aussi assurez vous que vous utilisez la bonne url selon que vous soyez passez en production ou que vous soyez toujours en développement.

**Comment by faso-dev** [comment]
Orange n'accepte plus les tests via localhost. Il faut deployer sur un serveur distant pour effectuer les tests.

**Comment by saifonglee** [comment]
Bonjour @faso-dev , merci pour ton assistance. Je vais donc faire ça.
