### ISSUE TITLE
Make  api response more frendly

### ISSUE THREAD

**Issue by issadicko** [faso-dev/orange-money-burkina-sdk#7]
https://github.com/faso-dev/orange-money-burkina-sdk/blob/462b95b9a15dec73e511349d1ca9303ced675d37/src/Fasodev/Sdk/OMSDK.php#L121

Hello, everybody!
I think we can make the response more friendly by returning an object from a class **OMResponse** 'for example' having well-determined fields for example "status", "content/message", "header", "error" with getters.

if you want I can propose a pull request for this very soon. 

Thanks!

**Comment by issadicko** [comment]
And  I think this will fix this https://github.com/faso-dev/orange-money-burkina-sdk/issues/6#issue-789332198 one

**Comment by issadicko** [comment]
And  I think this will fix this https://github.com/faso-dev/orange-money-burkina-sdk/issues/6#issue-789332198

**Comment by tsommie** [comment]
I thinking about creating a package for the same purpose, but since there is one existing already I would like to contribute to make it better, so my question is this:

1. Is it still maintained active? 
2. Where can I find the documentation of Orange Money API implementation so that I can understand what we are trying to achieve with this package?
@faso-dev

**Comment by yenteck** [comment]
Hi @tsommie  the repo is actively maintained. 
You can contribute .
For the documentation we use some materials we got from OM Burkina when we were trying to implement the api.

**Comment by yenteck** [comment]
Hi @issadicko can you propose something for this issue ?
I think @faso-dev  will be happy to merge your PR

**Comment by tsommie** [comment]
> Hi @tsommie the repo is actively maintained.
> You can contribute .
> For the documentation we use some materials we got from OM Burkina when we were trying to implement the api.

Can I get the documentation? It would help me understand what to do with the code.

**Comment by yenteck** [comment]
Your mail?

**Comment by tsommie** [comment]
> Your mail?

anitchec.dev@gmail.com

Also, i noticed you are using `declare(strict_types=1);` and class constant visibility which is only allowed in PHP 7 but your composer.json file supports PHP 5. You can remove these things if your concerned about PHP backward compatibility or you can bump PHP version from `>=5` to `^7.0`.

**Comment by yenteck** [comment]
Yeah ! Right . You can propose a PR for all that corrections

**Comment by tsommie** [comment]
> Yeah ! Right . You can propose a PR for all that corrections



> Yeah ! Right . You can propose a PR for all that corrections

Ok...I can only make one pull request at a time.

**Comment by tsommie** [comment]
> Yeah ! Right . You can propose a PR for all that corrections

Done!

**Comment by tsommie** [comment]
I tried to run the example.php file without an internet connection to see if I would run into this problem, but with the updates on the repository it will be caught but won't return any error messages or code, so you can do the following if you want a more friendly response:

```php
try {
    $orangeMoneyAPI = new OrangeMoneyAPI(
        env('ORANGE_MONEY_USERNAME'),
        env('ORANGE_MONEY_PASSWORD'),
        env('ORANGE_MONEY_MERCHANT_ID')
    );

    $orangeMoneyAPI->setAmount(1000) // Montant de la transaction
        ->setOTPCode(121212) // Code otp fourni par l'utilisateur
        ->setClientNumber(76819212); // Le numero de client

    $sdk = new PaymentSDK($orangeMoneyAPI);

    $result = $sdk->handlePayment(); //Enclenchement du processus de paiement

    echo "paiement effectué";
    echo $result->transID;

} catch (PaymentSDKException $exception) {
    if (trim($exception->getMessage()) != '') {
          echo "Whoops! Unable to process payment. <br /> Error message returned by request: {$exception->getMessage()}. <br /> Error code returned by request: {$exception->getCode()}";
    } else {
        echo "Unable to reach Orange Money servers, please check your internet connection.";
    }
}
```

@issadicko  This should close this issue yes?
